### ISSUE TITLE
Not Found on Search

### ISSUE THREAD

**Issue by dvarrazzo** [pgxn/pgxn-api#28]
1. Go on pgxn.org
2. search for "json" -> http://pgxn.org/search?q=json&in=docs
3. the first hit is "Test types" (www_fdw 0.1.6)
4. click on the first link -> http://pgxn.org/dist/www_fdw/test/readme.html
5. not found

**Comment by theory** [comment]
Fixed in pgxn/pgxn-site@e13a1f9.
